services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: patientor-front-dev

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    container_name: patientor-back-dev

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    container_name: nginx-proxy
    depends_on:
      - frontend
      - backend
